### ISSUE TITLE
Provide std::error::Error impl for errors

### ISSUE THREAD

**Issue by dtolnay** [gifnksm/lcov#26]
Missing std::error::Error impls make it awkward to use lcov with error handling libraries that are built around std::error::Error. See https://github.com/shepmaster/snafu/issues/214.

This applies to:

- lcov::reader::Error
- lcov::report::MergeError
- lcov::report::ParseError
- lcov::record::ParseRecordError
- lcov::record::ParseRecordKindError

**Comment by gifnksm** [comment]
Thank you for reporting.
The fix was released as lcov v0.6.0.
